<?php
    $part1English = array('', 'Last calibration certificate of fixed gas detector', 
    'Last calibration certificate of UTI equipment', 
    'Last calibration certificate of oxygen measurement equipment', 
    'Cargo tanks cleaning certificate', 
    'Brake holding capacity and rendering test certificate', 
    'Certificates of all mooring ropes and tails', 
    'Records of inspection or maintenance of mooring ropes and mooring equipment', 
    'Records of the last test and/or calibration of the safety valves of the cargo tanks', 
    'Last test of load certificate of crane', 
    'Record or evidence of last tests performed on cargo system&#39;s equipment and alarms (ESD, HiHi, etc).');
    
    $part1Spanish = array('', 'Certificado de la última calibración del detector fijo de gases', 
    'Último certificado de calibración del equipo UTI', 
    'Último certificado de calibración del equipo medidor de oxígeno', 
    'Certificado de limpieza de tanques de carga', 
    'Certificado de prueba de capacidad y rendimiento de los frenos de los winches', 
    'Certificados de líneas de amarre y colas', 
    'Registros de inspección o mantenimiento de los cabos y equipos de amarre', 
    'Registro de la última prueba y/o calibración de las válvulas de seguridad de los tanques de carga', 
    'Certificado de última prueba de carga de la grúa', 
    'Registro o evidencia de las últimas pruebas realizadas a sus equipos y alarmas de carga (ESD, HiHi, etc).');
    
    $part2English = array('', 'The mooring lines are adequate for conditions at terminal', 
    'The mooring winches are adequate and fully operative', 
    'The overboard or sea valves are sealed or lashed in closed position, Annex I & II', 
    'High level and overfill alarms of all cargo tanks were tested and operating properly', 
    'The automatic shutdown system of the vessel has been tested and found to be operating properly', 
    'Are the vessel&#39;s tanks inerted?', 
    'The inert gas system or N2 supply on board is operative and work without any observation (discharging operations only)?', 
    'Vapor pressure inside cargo tanks is appropriate for loading operations (recommendable less than 40 mbar for loading operations only)?', 
    'The firefighting system is fully operative and tested', 
    'The vessel has adequate coupling or reducer to connect the terminal loading arm, vapour recovery line and hoses flanges', 
    'Oily water separator overboard valve sealed', 
    'Sewage plant overboard valve locked sealed', 
    'Pilot confirmed bridge vessel equipment have been fully tested, ready for maneuvering and signed the Pilot Card satisfactorily', 
    'Mooring tails are fitted to mooring lines, are they correctly fitted?', 
    'The fixed gas detector alarms were tested and operating properly', 
    'The electric motor room air lock alarms were tested and operating properly', 
    'The safety relief or P/V valves are properly marked', 
    'The deck spray system was tested and operating properly', 
    'Loading Master informed to the Captain and Pilot the terminal&#39;s sign posting condition and the weather conditions for maneuvers', 
    'Navigation charts/ECDIS used to access the TMPC are in force', 
    'Mooring plan has been checked and duly agreed by the Loading Master, Captain and Pilot');
    
    $part2Spanish = array('', 'Las líneas de amarre son adecuadas para las condiciones en el Terminal', 
    'Los winches de amarre están completamente operativos', 
    'Las válvulas de fuera de borda o de mar están selladas y aseguradas en posición de cierre, anexo I y II', 
    'Las alarmas de alto nivel y sobrellenado de los tanques de carga del buque fueron probadas y operan adecuadamente.', 
    'El sistema de parada automático del buque ha sido probada y se encuentra operando apropiadamente', 
    '¿Están los tanques del buque inertizados?', 
    '¿El sistema de gas inerte o abastecimiento de N2 a bordo se encuentra operativo y trabaja sin observaciones (solo para operaciones de descarga)?', 
    '¿La presión de vapor en los tanques de carga es la adecuada para las operaciones de carga (recomendable menor a 40 mbar solo para operaciones de carga)?', 
    'El sistema contra incendio está completamente probado y operativo.', 
    'El buque cuenta con las reducciones para la conexión de los brazos, línea de vapores y manguera de carga', 
    'La válvula de descarga fuera de borda del separador de aguas oleosas, ¿está sellada?', 
    'La válvula de descarga fuera de borda de planta de tratamiento de aguas servidas, ¿está sellada?', 
    'El Práctico confirma que los equipos del puente de comando han sido probados, están listos para la maniobra y ha firmado la Cartilla de Práctico satisfactoriamente', 
    '¿Las colas de amarre están sujetas de forma correcta a las líneas de amarre?', 
    'Las alarmas del equipo detector de gases fijo del buque fueron probadas y operan adecuadamente', 
    'Las alarmas del Air Lock del cuarto de motores eléctricos fueron probadas y operan correctamente', 
    'Las válvulas de seguridad o presión y vacío están correctamente marcadas', 
    'El sistema de rociadores de cubierta fue probado y opera correctamente', 
    'El Loading Master informó al Capitán y Práctico, la condición de la señalización del terminal y sobre las condiciones oceanográficas para la maniobra', 
    'Las cartas de navegación/ECDIS utilizadas para acceder al TMPC se encuentran vigentes.', 
    'El plan de amarre ha sido revisado y debidamente acordado por el Loading Master, Capitán y Práctico Marítimo.');
?>